CREATE TABLE CANCION (	
    ID NUMBER(38,0) PRIMARY KEY, 
    NOMBRE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	DURACION NUMBER(38,0) NOT NULL ENABLE, 
	FECHA_LANZAMIENTO DATE NOT NULL ENABLE
);

CREATE SEQUENCE  
    ID  
MINVALUE 1 
MAXVALUE 99999 
INCREMENT BY 1;